blank_issues_enabled: false
contact_links:
  - name: "ğŸ“š Read Jina Docs"
    url: https://docs.jina.ai/
    about: Find your solution from our documenations
  - name: "ğŸ£ Learn by Examples"
    url: https://github.com/jina-ai/examples
    about: Learn from real-world examples
  - name: "ğŸš Contributing Guideline"
    url: https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md
    about: Learn from real-world examples
  - name: "ğŸ” Search on Existing Issues"
    url: https://github.com/jina-ai/jina/search?q=&type=Issues
    about: Someone else may already post this issue and got solved