apiVersion: v1
kind: ConfigMap
metadata:
  namespace: postgres
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "postgresdb"
  POSTGRES_USER: "postgresadmin"
  POSTGRES_PASSWORD: "1235813"
