name: Autocommit

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:


jobs:
  autocommit:
    if: |
      !startsWith(github.event.head_commit.message, 'chore') &&
      !startsWith(github.event.head_commit.message, 'build: hotfix') &&
      !endsWith(github.event.head_commit.message, 'reformatted by jina-dev-bot')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.JINA_DEV_BOT }}
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git config --local user.email "dev-bot@jina.ai"
          git config --local user.name "Jina Dev Bot"
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Generate TOC
        uses: technote-space/toc-generator@v3
        with:
          MAX_HEADER_LEVEL: 2
          GITHUB_TOKEN: ${{ secrets.JINA_DEV_BOT }}
          COMMIT_NAME: Jina Dev Bot
          COMMIT_EMAIL: dev-bot@jina.ai
          TOC_TITLE: ''
          TARGET_PATHS: 'CHANGELOG.md,CONTRIBUTING.md,RELEASE.md'
          CHECK_ONLY_DEFAULT_BRANCH: true
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.JINA_DEV_BOT }}
          branch: master
