name: Copyright

on:
  push:
    branches:
      - master

jobs:
  update-copyright:
    if: "!startsWith(github.event.head_commit.message, 'chore')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.JINA_DEV_BOT }}
      - run: |
          git fetch --prune --unshallow
          git config --local user.email "dev-bot@jina.ai"
          git config --local user.name "Jina Dev Bot"
      - uses: VinnyBabuManjaly/copyright-action@v1.0.0
        with:
          CopyrightString: '__copyright__ = "Copyright (c) 2020 Jina AI Limited. All rights reserved."\n__license__ = "Apache-2.0"\n\n'
          FileType: '.py'
          Path: 'jina/'
      - run: |
          git add -u
          git commit -m "chore: update copyright header"
          git status
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JINA_DEV_BOT }}
          force: true