name: Docker BuildX

on:
  push:
    branches:
      - master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build the docs
        run: |
          ./make-doc.sh commit "${{github.event_name}} ${{github.sha}}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          repository: jina-ai/jina-docs
          force: true
          directory: docs/_build/html
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Available platforms
        run: |
          echo ${{ steps.buildx.outputs.platforms }}
      - name: Run Buildx and Upload to Docker Cloud
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6 \
            --output "type=registry" \
            -t jinaai/jina:master-debian -t jinaai/jina:dev-debian \
            --file ./Dockerfiles/debianx.Dockerfile .
